language: objective-c
osx_image: xcode7.3
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - IOS_SDK=iphonesimulator9.3
  - TVOS_SDK=appletvsimulator9.3
before_install:
  - brew update
  - brew reinstall xctool
script:
  - xcodebuild -showsdks
  - xctool -project Project/Player.xcodeproj -scheme 'Debug - iOS' -sdk '$IOS_SDK' build analyze
#  - xctool -project Project/Player.xcodeproj -scheme 'Debug - tvOS' -sdk '$TVOS_SDK' build analyze
