language: objective-c
osx_image: xcode9.4
xcode_workspace: Player.xcworkspace
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - CONFIG=Release
  - XCCONFIG=Project/Shared/Travis.xcconfig
matrix:
  include:
    - env:
        ACTION=test:macos
        SDK=macosx10.13
      install:
        - gem install xcpretty
    - env:
        ACTION=build:xcodebuild:ios
        SDK=iphonesimulator11.4
      install:
        - gem install xcpretty
    - env:
        ACTION=build:xcodebuild:tvos
        SDK=appletvsimulator11.4
      install:
        - gem install xcpretty
    - env: ACTION=build:carthage
    - env: ACTION=build:pod
    - env: ACTION=swiftlint
#fast_finish: true
script: rake "$ACTION"
